### ISSUE TITLE
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1970: illegal multibyte sequence

### ISSUE THREAD

**Issue by toyxyz** [huchenlei/ComfyUI_DanTagGen#1]
When I installed the custom node, I got the following error 

Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_DanTagGen\__init__.py", line 1, in <module>
    from .dan_tag_gen import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_DanTagGen\dan_tag_gen.py", line 4, in <module>
    from .lib_dantaggen.app import get_result
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_DanTagGen\lib_dantaggen\app.py", line 11, in <module>
    import gradio as gr
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1059, in read_text
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1970: illegal multibyte sequence

Cannot import C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI_DanTagGen module for custom nodes: 'cp949' codec can't decode byte 0xe2 in position 1970: illegal multibyte sequence

**Comment by huchenlei** [comment]
Gradio dependency removed in https://github.com/huchenlei/ComfyUI_DanTagGen/commit/861e344e19d7192449f3166a7d13cf4b22961a16.
