### ISSUE TITLE
After installation, running the comfyui results in an error

### ISSUE THREAD

**Issue by Simwake** [huchenlei/ComfyUI_DanTagGen#8]
After installing the plugin, when I run ComfyUI, it shows the following error:
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_DanTagGen\__init__.py", line 1, in <module>
    from .dan_tag_gen import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_DanTagGen\dan_tag_gen.py", line 4, in <module>
    from .lib_dantaggen.app import get_result
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_DanTagGen\lib_dantaggen\app.py", line 14, in <module>
    from .kgen.generate import tag_gen
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_DanTagGen\lib_dantaggen\kgen\generate.py", line 5, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

**I then attempted to install llama-cpp-python internally in ComfyUI, but encountered the following error during installation**

Building wheel for llama-cpp-python (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
    *** scikit-build-core 0.9.9 using CMake 3.29.0 (wheel)
    *** Configuring CMake...
    2024-08-02 14:11:54,653 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
    loading initial cache file C:\Users\Administrator\AppData\Local\Temp\tmpz06hgp6v\build\CMakeInit.txt
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Running

       'nmake' '-?'

      failed with:

      no such file or directory

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!

    *** CMake configuration failed
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama-cpp-python)

**Comment by Simwake** [comment]
Alright, after installing MSVC, Windows 11 SDK, C++ CMake, and updating CMake to the latest version, reinstalling llama-cpp-python worked
